import enum

class Speciality(enum.Enum):
    CARDIOLOGY = "CARDIOLOGY"
    DERMATOLOGY = "DERMATOLOGY"
    ORTHOPEDICS = "ORTHOPEDICS"
    PEDIATRICS = "PEDIATRICS"
    PSYCHIATRY = "PSYCHIATRY"
    GYNECOLOGY = "GYNECOLOGY"
    NEUROLOGY = "NEUROLOGY"
    GENERAL_PRACTICE = "GENERAL_PRACTICE"
    UROLOGY = "UROLOGY"

class CancellationReason(enum.Enum):
    PATIENT_CANCELED = "PATIENT_CANCELED"
    DOCTOR_CANCELED = "DOCTOR_CANCELED"
    OTHER = "OTHER"

class Sector(enum.Enum):
    RECEPTION = "RECEPTION"
    FINANCE = "FINANCE"
    MANAGEMENT = "MANAGEMENT"
    IT = "IT"
    OTHER = "OTHER"
    