import enum

class Speciality(enum.Enum):
    CARDIOLOGISTA = "CARDIOLOGISTA"
    DERMATOLOGIA = "DERMATOLOGIA"
    ORTOPEDIA = "ORTOPEDIA"
    PEDIATRIA = "PEDIATRIA"
    PSIQUIATRIA = "PSIQUIATRIA"
    GINECOLOGIA = "GINECOLOGIA"
    NEUROLOGIA = "NEUROLOGIA"
