import enum

class Speciality(enum.Enum):
    CARDIOLOGY = "CARDIOLOGY"
    DERMATOLOGY = "DERMATOLOGY"
    ORTHOPEDICS = "ORTHOPEDICS"
    PEDIATRICS = "PEDIATRICS"
    PSYCHIATRY = "PSYCHIATRY"
    GYNECOLOGY = "GYNECOLOGY"
    NEUROLOGY = "NEUROLOGY"
    GENERAL_PRACTICE = "GENERAL_PRACTICE"
    UROLOGY = "UROLOGY"
